on:
  push:
    branches:
      - main  # O workflow será executado sempre que algo for 'pushado' para o branch 'main'
  pull_request:
    branches:
      - main  # Também será executado quando um pull request for feito para o branch 'main'

jobs:
  latex:
    runs-on: ubuntu-latest  # Usa uma imagem do Ubuntu no GitHub Actions

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2  # Faz o checkout do código do repositório

      - name: Set up TeX Live
        run: sudo apt-get install -y texlive-latex-recommended texlive-fonts-recommended texlive-lang-portuguese texlive-lang-english texlive-lang-french texlive-lang-spanish texlive-latex-extra texlive-bibtex-extra texlive-science texlive-pictures texlive-xetex texlive-font-utils texlive-extra-utils texlive-lang-other  # Instala o pacote TeX Live completo (pode ser pesado)

      - name: Install abntex2 package
        run: |
          git clone https://github.com/abntex/abntex2.git
          sudo cp -r abntex2/* /usr/share/texlive/texmf-dist/tex/latex/
          sudo mktexlsr  # Atualiza os caminhos dos pacotes TeX

      - name: Compile LaTeX document
        run: pdflatex doc_p1.tex  # Substitua 'doc_p1.tex' pelo nome do seu arquivo LaTeX

      - name: Upload PDF artifact
        uses: actions/upload-artifact@v3
        with:
          name: LaTeX-PDF
          path: doc_p1.pdf
